#!/bin/bash

d="${0%/*}"

out_dir="out/"
src_dir="src/"

if [ ! -d "$d/$out_dir" ]
then
	echo "Create ouput dir \"$out_dir\"" >&2
	mkdir "$d/$out_dir"
fi

sources="$(find $d/$src_dir -name "*.java")"

javac -Xlint:all -Xdiags:verbose -d $d/$out_dir -sourcepath $d/$src_dir $sources

