#!/bin/bash

out_dir="out/"
src_dir="src/"


# USAGE: die MESSAGE CODE
die() {
	printf "$1\n" >&2
	exit $2
}

if [ ! -d "$out_dir" ]
then
	echo "Create ouput dir \"$out_dir\"" >&2
	mkdir "$out_dir"
fi

# Retrieve the javac command
javac="$(which javac)"
if [ -z "$javac" ]
then
	die "'javac' executable not found" 255
fi

$javac -Xlint:all -d $out_dir -sourcepath $src_dir $src_dir/*/*/*.java

