#!/bin/bash

d=${0%/*}

out_d="$d/out"
src_d="$d/src"

shopt -s nullglob


files=

for path_f_class in $out_d/joH1/oo_rpg/*
do
	f_class=${path_f_class##*/}
	f=${f_class%.*}
	files="$files joH1.oo_rpg.$f "
done

if [ -z "$files" ]
then
	echo "output directory '$out_d' is empty" >&2
	exit 1
fi

(cd $out_d; serialver $files 2>/dev/null)
